# List all Local Authority codes
SELECT DISTINCT ?s ?p
WHERE {
        ?s ?p <http://example.org/dataShuttle/LAD>
}

# More details about a specific LAD:
SELECT DISTINCT ?p ?o
WHERE {
        <http://example.org/dataShuttle/LAD/41UE> ?p ?o
}

# List all ICD ranges (labels and uris)
SELECT DISTINCT ?label ?uri
WHERE { 
        ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?label .
        ?uri <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://example.org/dataShuttle/icd10/range>
}

# List genders (labels and uris)
SELECT DISTINCT ?label ?uri
WHERE { 
        ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?label .
        ?uri <http://www.w3.org/2000/01/rdf-schema#subClassOf> <http://example.org/dataShuttle/gender>
}

# Get all data about one particular statistic
SELECT DISTINCT ?predicate ?object
WHERE { 
        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> ?predicate ?object
}

# Get all data about one particular statistic - fetching human readable labels. @TODO: refine, as it seems to return more than one result.
SELECT DISTINCT ?value ?agerange ?icd10range ?year ?gender ?areacode
WHERE { 
        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> ?value .
        
        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> <http://purl.org/NET/scovo#dimension> ?agerangeuri .
        ?agerangeuri rdfs:subClassOf <http://example.org/dataShuttle/age/range> .
        ?agerangeuri rdfs:label ?agerange .

        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> <http://purl.org/NET/scovo#dimension> ?icd10rangeuri .
        ?icd10rangeuri rdfs:subClassOf <http://example.org/dataShuttle/icd10/range> .
        ?icd10rangeuri rdfs:label ?icd10range .

        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> <http://purl.org/NET/scovo#dimension> ?yearuri .
        ?yearuri rdfs:subClassOf <http://example.org/dataShuttle/Year> .
        ?yearuri rdfs:label ?year .

        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> <http://purl.org/NET/scovo#dimension> ?genderuri .
        ?genderuri rdfs:subClassOf <http://example.org/dataShuttle/gender> .
        ?genderuri rdfs:label ?gender .

        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> <http://purl.org/NET/scovo#dimension> ?areacodeuri .
        ?areacodeuri rdfs:subClassOf <http://example.org/dataShuttle/LAD> .
        ?areacodeuri rdfs:label ?areacode .
}


# Get all data filtering on year 2008 and gender male. Display local Authority Code and the statistical value.
SELECT DISTINCT ?lad ?stat
WHERE {
        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> ?stat .
        <http://example.org/dataShuttle/vs3-2008/N00-N16/H12UC/2008/M> <http://purl.org/NET/scovo#dimension> ?areacodeuri .
        ?areacodeuri rdfs:subClassOf <http://example.org/dataShuttle/LAD> .
        ?areacodeuri rdfs:label ?lad .
}

# Get all URIs for stats over 100 - limit 20, descending order
SELECT DISTINCT ?uri ?stat
WHERE {
        ?uri <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> ?stat .
        FILTER (?stat >= 100)
}
ORDER BY DESC(?stat)
LIMIT 20

# Get all areacodes beginning with H
SELECT DISTINCT ?areacode
WHERE {
        ?s ?p <http://example.org/dataShuttle/LAD> .
        ?s rdfs:label ?areacode .
        FILTER(regex(?areacode, "^H"))
}
ORDER BY ?areacode
